/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import static Home.Menu_table.a;
import static Home.Menu_table.b;
import static Home.Menu_table.c;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import com.mysql.cj.protocol.Resultset;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSetMetaData;

/**
 *
 * @author Lenovo
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    static String user = Login_Form.us;
    public Cart() {
        initComponents();
        table_show();
        //Tabledata();
    }
    Connection con1=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    int cname = 1 ;
    public Cart(int Cname) {
        initComponents();
       //conn=javaconnect.ConnecrDb();
        cname = Cname ;
        table_show();
        
       //update_table();
    }
    
    DefaultTableModel model ;
    private void table_show() {
           int c;
           try {
                Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
             pst = con1.prepareStatement("SELECT p.name ,pt.cartid,pt.price,pt.mobile,pt.address  FROM menu_table as pt inner join menu as p where username ='"+user+"' and pt.mid = p.id");
            rs = pst.executeQuery();
            model = (DefaultTableModel)jTable1.getModel();
            double total=0;
             while(rs.next())
            {
                String pn = rs.getString("name");
              int crtid = rs.getInt("cartid");
                float pr = rs.getFloat("price");
                total+=pr;
                String phn = rs.getString("mobile");
                String add = rs.getString("address");
                Object[] obj={crtid,pn,pr,phn,add};
                model.addRow(obj);
            }
             String np="";
             np=total+"";
             TotalLbl.setText(np);
             
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TotalLbl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("MY CART");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 145, -1));

        jTable1.setBackground(new java.awt.Color(0, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CART ID", "NAME", "PRICE", "MOBILE", "ADDRESS"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 527));

        TotalLbl.setBackground(new java.awt.Color(0, 102, 102));
        TotalLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 170, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setText("Total");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 60, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 120, 40));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 120, 40));
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 170, -1));
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 170, -1));
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 240, 170, -1));
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 290, 170, -1));
        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cart ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 93, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Item Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 37, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mobile");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Customer_portal frm=new Customer_portal(cname);
        System.out.println(cname);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
       
        // txtphoto1.setIcon(Df.getValueAt(selectedIndex, 6).toString());
       // txtphoto1.setIcon(format);
          
        
        // FetchPhoto();
         
      //  int row=Table1.getSelectedRow();
       int vv=jTable1.getSelectedColumn();
       String tc=jTable1.getModel().getValueAt(selectedIndex, 1).toString();
       
        try{
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
           String query="select * from menu_cart where cartid="+tc+"";
           pst=con1.prepareStatement(query);
           ResultSet rs=pst.executeQuery();
           
             if(rs.next()){
           String cartid=rs.getString("cartid");  
           String items=rs.getString("items");
           //String id=rs.getString("id");
           String price=rs.getString("price");
           String mobile=rs.getString("mobile");
           String address=rs.getString("address");
           
           
              
              //String photo1=rs.getString("photo");
              //byte[] image=rs.getBytes("photo");
              //format =new ImageIcon(image);
              //txtphoto1.setIcon(format);
              a.setText(cartid);
             
              b.setText(items);
              e.setText(price);
              c.setText(mobile);
               d.setText(address);
              
              //txtolocation.setText(location);
              //txtofees.setText(fees);
              //txtofacilities.setText(facilities);
              //txtphoto2.setText(photo1);
              pst.close();
              rs.close();
             }
              
             
           
        }
        catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }


           a.setText(Df.getValueAt(selectedIndex, 0).toString());
        b.setText(Df.getValueAt(selectedIndex, 1).toString());
        //  tc=Table1.getModel().getValueAt(selectedIndex, 1).toString();
         e.setText(Df.getValueAt(selectedIndex, 2).toString());
       // tc=Integer.valueOf(Df.getValueAt(selectedIndex, 1).toString());
         c.setText(Df.getValueAt(selectedIndex, 3).toString());
         //txtolocation.setText(Df.getValueAt(selectedIndex, 3).toString());
         d.setText(Df.getValueAt(selectedIndex, 4).toString());
         //txtofees.setText(Df.getValueAt(selectedIndex, 4).toString());
         //txtofacilities.setText(Df.getValueAt(selectedIndex, 5).toString());
        //txtphoto2.setText(Df.getValueAt(selectedIndex, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cartid=a.getText();
        String items =b.getText();
        String total =e.getText();
        String mobile =c.getText();
        String address =d.getText();
        
        //String mobile=phn.getText();
  java.sql.PreparedStatement push;
       // String photo =txtphoto2.getText();
       // String username =txtousername1.getText();
       if(cartid.isEmpty()||items.isEmpty()||total.isEmpty()||mobile.isEmpty()||address.isEmpty()){
            JOptionPane.showMessageDialog(this,"Every field must be filled up.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
             
                Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
               //int regi = Integer.valueOf(regno);
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
                //pst = con1.prepareStatement("Select * from caterer1 WHERE regno = ? AND mobile = ?");
                //pst.setInt(1, regi);
                //pst.setString(2,mobile);
            
            
            //ResultSet res = pst.executeQuery();
            //if(res.next()){
                 
                push = con1.prepareStatement("insert into menu_cart (cartid,items,total,mobile,address)values(?,?,?,?,?)");
               push.setString(1,cartid); 
               push.setString(2,items);
               push.setString(3,total);
               push.setString(4,mobile);
               push.setString(5,address);
               
               
               
               //push.setBytes(7,photo);

            
              push.executeUpdate();
              JOptionPane.showMessageDialog(this, "Record Saved");
            
            
            a.setText(""); 
            b.setText("");
           e.setText("");
            c.setText("");
            d.setText("");
            
            
            
            //txtphoto2.setText("");
            a.requestFocus();
            //table_show();
            //update_table();
            
            
             
            }
            catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TotalLbl;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
 //private void Tabledata(){
    
//        try{
//        Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
//                con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
//            pst = con1.prepareStatement("select * from package_table");
//        
//        ResultSet res = pst.executeQuery();
//        
//        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
//        
//        int total = 0 ;
//        
//        while(res.next()) {
//            String c_id = String.valueOf(res.getInt("cartid"));
//            String package_id = String.valueOf(res.getInt("pid"));
//            String quan = String.valueOf(res.getInt("pquan"));
//            String un = String.valueOf(res.getString("username"));
//            String mb = String.valueOf(res.getString("mobile"));
//            String ad = String.valueOf(res.getString("address"));
//            
//            if(un.equals(uname)) {
//                total += Integer.valueOf(quan);
//                PreparedStatement tt = (PreparedStatement) 
//                    con1.prepareStatement("Select * from package");
//                ResultSet r1 = tt.executeQuery();
//                String packagename = "";
//                while(r1.next()) {
 //                  String p_id = String.valueOf(r1.getInt("package_id"));
 //                   String package_name = r1.getString("packagename");
 //                   if(package_id.equals(p_id)) {
 //                       packagename = package_name ;
 //                       break;
 //                   }
 //               }
//
 //              String tbdata[] = {c_id, packagename,quan} ;
  //              tblModel.addRow(tbdata);
               //jButton3.setEnabled(true);
 //          }
 //       }
 //      jTextField1.setText(String.valueOf(total));
 //       } 
 //       catch (ClassNotFoundException ex) {
 //           java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 //      } catch (SQLException ex) {
 //           java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 //       }
 //}
     
   
    private void DeleteItem(int cid) {
        try{
             Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
            pst = con1.prepareStatement("DELETE FROM package_table WHERE cartid = ? ");
            pst.setInt(1,cid);
            pst.executeUpdate();
            
            
        }
       
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
        
          
        
       
        
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

