/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo
 */
import com.mysql.cj.protocol.Resultset;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import java.sql.*;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
public class Package extends javax.swing.JFrame {

    /**
     * Creates new form Package
     */ Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public Package() {
        initComponents();
           
       update_table();
    }
     String cname = "" ;
    public Package(String Cname) {
        initComponents();
       //conn=javaconnect.ConnecrDb();
        cname = Cname ;
       update_table();
    }
    
   private void update_table(){
       int rg = -1 ;
        try{
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
        PreparedStatement st = (PreparedStatement) 
                con1.prepareStatement("Select * from caterer1 where name = ?");
        st.setString(1, cname);
       // st.setInt(1, rg);
        ResultSet res = st.executeQuery();
        if(res.next()) {
           
           rg = res.getInt("regno");
  
        }
        } 
           catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            conn = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
        String sql="select * from package where regno = ?";
        pst=conn.prepareStatement(sql);
        pst.setInt(1,rg);
        
        rs=pst.executeQuery();
        Tablemouse.setModel(DbUtils.resultSetToTableModel(rs));
        
    }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        pc = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        dltbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablemouse = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("Name    :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("ID          :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setText("Price    :");

        addbtn.setBackground(new java.awt.Color(0, 102, 102));
        addbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        editbtn.setBackground(new java.awt.Color(0, 102, 102));
        editbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        editbtn.setForeground(new java.awt.Color(255, 255, 255));
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        dltbtn.setBackground(new java.awt.Color(0, 102, 102));
        dltbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        dltbtn.setForeground(new java.awt.Color(255, 255, 255));
        dltbtn.setText("Delete");
        dltbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\ilish2.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setText("Reg No:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setText("Mobile:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setText("Details  :");

        dt.setColumns(20);
        dt.setRows(5);
        jScrollPane2.setViewportView(dt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dltbtn)))
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editbtn)
                    .addComponent(addbtn)
                    .addComponent(dltbtn))
                .addGap(18, 18, 18)
                .addComponent(backbtn)
                .addGap(14, 14, 14))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        Tablemouse.setBackground(new java.awt.Color(102, 255, 204));
        Tablemouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "REG NO", "NAME", "DETAILS", "ID", "PRICE", "MOBILE"
            }
        ));
        Tablemouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablemouseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablemouse);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Connection con1;
PreparedStatement insert;
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        int rgi = -1 ;
        try{
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
        PreparedStatement st = (PreparedStatement) 
                con1.prepareStatement("Select * from caterer1 where name = ?");
        st.setString(1, cname);
        ResultSet res = st.executeQuery();
        if(res.next()) {
           
           rgi = res.getInt("regno");
  
        }
        } 
           catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
         String regno =rg.getText();
         String name =nm.getText();
         String detail =dt.getText();
        
        String id =d.getText();
        String price =pc.getText();
        String mobile =phn.getText();
  java.sql.PreparedStatement push;
       // String photo =txtphoto2.getText();
       // String username =txtousername1.getText();
       if(regno.isEmpty()||name.isEmpty()|| detail.isEmpty()|| id.isEmpty()||price.isEmpty()||mobile.isEmpty()){
            JOptionPane.showMessageDialog(this,"Every field must be filled up.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
             
                Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
                int regi=Integer.valueOf(regno);
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
                 insert = con1.prepareStatement("Select * from caterer1 WHERE regno = ? AND mobile = ?");
            insert.setInt(1,regi);
            insert.setString(2,mobile);
            
            
            ResultSet res = insert.executeQuery();
             if(res.next()){
               
                //con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
               push = con1.prepareStatement("insert into package (regno,name,detail,id,price,mobile)values(?,?,?,?,?,?)");
               push.setString(1,regno);
               push.setString(2,name);
               push.setString(3,detail);
               push.setString(4,id);
               push.setString(5,price);
               push.setString(6,mobile);
               
               //push.setBytes(7,photo);

            
              push.executeUpdate();
              JOptionPane.showMessageDialog(this, "Record Saved");
            
           rg.setText(""); 
           nm.setText("");
           dt.setText("");
           d.setText("");
           pc.setText("");
           phn.setText("");
            
            //txtphoto2.setText("");
            rg.requestFocus();
           update_table();
            
            
             
            }
             else{
                JOptionPane.showMessageDialog(this,"Registration  not found.", "Error", JOptionPane.ERROR_MESSAGE);
             }
            }
            catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void TablemouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablemouseMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        // TODO add your handling code here:
        // FetchPhoto();
        int rgi = -1 ;
        try{
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
        PreparedStatement st = (PreparedStatement) 
                con1.prepareStatement("Select * from caterer1 where name = ?");
        st.setString(1, cname);
        ResultSet res = st.executeQuery();
        if(res.next()) {
           
           rgi = res.getInt("regno");
  
        }
        } 
           catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        DefaultTableModel Df = (DefaultTableModel) Tablemouse.getModel();
        int selectedIndex = Tablemouse.getSelectedRow();
        
       
        // txtphoto1.setIcon(Df.getValueAt(selectedIndex, 6).toString());
       // txtphoto1.setIcon(format);
          
        
        // FetchPhoto();
         
      //  int row=Table1.getSelectedRow();
       int vv=Tablemouse.getSelectedColumn();
       String tc=Tablemouse.getModel().getValueAt(selectedIndex, 1).toString();
       
        try{
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
           String query="select * from package where id="+tc+"";
           insert=con1.prepareStatement(query);
           ResultSet rs=insert.executeQuery();
           
              String regno=rs.getString("regno");
              String name=rs.getString("name");
              String detail=rs.getString("dt");
               String id=rs.getString("id");
              String price=rs.getString("price");
              String mobile=rs.getString("mobile");
              //String photo1=rs.getString("photo");
              //byte[] image=rs.getBytes("photo");
              //format =new ImageIcon(image);
              //txtphoto1.setIcon(format);
              rg.setText(regno);
              nm.setText(name);
              dt.setText(detail);
              d.setText(""+id);
              pc.setText(price);
              phn.setText(mobile);
              //txtolocation.setText(location);
              //txtofees.setText(fees);
              //txtofacilities.setText(facilities);
              //txtphoto2.setText(photo1);
              insert.close();
              rs.close();
             
              
             
           
        }
        catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }


         rg.setText(Df.getValueAt(selectedIndex, 0).toString()); 
         nm.setText(Df.getValueAt(selectedIndex, 1).toString());
        //  tc=Table1.getModel().getValueAt(selectedIndex, 1).toString();
        dt.setText(Df.getValueAt(selectedIndex, 2).toString());
         d.setText(Df.getValueAt(selectedIndex, 3).toString());
       // tc=Integer.valueOf(Df.getValueAt(selectedIndex, 1).toString());
       
         pc.setText(Df.getValueAt(selectedIndex, 4).toString());
         //txtolocation.setText(Df.getValueAt(selectedIndex, 3).toString());
         phn.setText(Df.getValueAt(selectedIndex, 5).toString());
         //txtofees.setText(Df.getValueAt(selectedIndex, 4).toString());
         //txtofacilities.setText(Df.getValueAt(selectedIndex, 5).toString());
        //txtphoto2.setText(Df.getValueAt(selectedIndex, 6).toString());
         
    }//GEN-LAST:event_TablemouseMouseClicked

    private void dltbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel) Tablemouse.getModel();
     
        int selectedIndex = Tablemouse.getSelectedRow();
        String regno =rg.getText();
        String name =nm.getText();
        String detail =dt.getText();
        String id =d.getText();
        String price =pc.getText();
        String mobile =phn.getText();
    
        if(regno.isEmpty()||name.isEmpty()||detail.isEmpty()|| id.isEmpty()||price.isEmpty()||mobile.isEmpty()){
            JOptionPane.showMessageDialog(this,"Every field must be filled up.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
        
        
            try {
                
               
           
 
            //Class.forName("com.mysql.cj.jdbc.Driver");
            // con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
            insert = con1.prepareStatement("Select * from caterer1 WHERE regno = ? AND mobile = ?");
            insert.setString(1,regno);
            insert.setString(2,mobile);
            
            
            ResultSet res = insert.executeQuery();
            if(res.next()){
                 int dialogResult = JOptionPane.showConfirmDialog (null, "Do you want to Delete the record","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
 
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            
           
            insert = con1.prepareStatement("delete from package where id = ? and regno = ?");
           insert.setString(1, id);
             insert.setString(2, regno);
           
           // insert.setInt(1,id); for auto 
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Delete");
             rg.setText("");
            nm.setText("");
            dt.setText("");
            d.setText("");
            pc.setText("");
             phn.setText("");
          
           // txtphoto1.setText("");
            rg.requestFocus();
            table_show();
           update_table();
            }
           
          }else{
                 JOptionPane.showMessageDialog(this,"Registration not matched", "Error", JOptionPane.ERROR_MESSAGE);
            }
            }
          
             
             catch (ClassNotFoundException ex) {
               
                java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Change Package id", "Error", JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
    }                  
    }//GEN-LAST:event_dltbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        this.hide();
        //System.out.println(cname);
        Caterer_portal frm=new Caterer_portal(cname);
        
        frm.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
         java.sql.PreparedStatement push;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
            String value1=rg.getText();
            String value2=nm.getText();
            String value3=dt.getText();
            String value4=d.getText();
            String value5=pc.getText();
            String value6=phn.getText();
            String sql="update package set regno='"+value1+"',name='"+value2+"',detail='"+value3+"',id='"+value4+"',price='"+value5+"',mobile='"+value6+"'where id='"+value4+"' and regno='"+value1+"'";
            push=con1.prepareStatement(sql);   
            push.execute();
            JOptionPane.showMessageDialog(null,"Updated");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
           update_table();
     
    }//GEN-LAST:event_editbtnActionPerformed
   private void table_show() {
       int rg = -1 ;
        try{
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
        PreparedStatement st = (PreparedStatement) 
                con1.prepareStatement("Select * from caterer1 where name = ?");
        st.setString(1, cname);
        ResultSet res = st.executeQuery();
        if(res.next()) {
           
           rg = res.getInt("regno");
  
        }
        } 
           catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
           int c;
           try {
                Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
           insert = con1.prepareStatement("SELECT * FROM package");
           ResultSet Rs = insert.executeQuery();
            ResultSetMetaData Rss = Rs.getMetaData();
            c = Rss.getColumnCount();
            DefaultTableModel Df = (DefaultTableModel) Tablemouse.getModel();
            Df.setRowCount(0);
            while (Rs.next()) {
                Vector v2 = new Vector();
          
                for (int ii = 1; ii <= c; ii++) {
                    v2.add(Rs.getString("regno"));
                    v2.add(Rs.getString("name"));
                   v2.add(Rs.getString("detail"));
                    v2.add(Rs.getString("id"));
                    v2.add(Rs.getString("price"));
                    v2.add(Rs.getString("mobile"));
                   
                    //v2.add(Rs.getString("location"));
                      
                }
              
                Df.addRow(v2);
            }

            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Package.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Package().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablemouse;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField d;
    private javax.swing.JButton dltbtn;
    private javax.swing.JTextArea dt;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField pc;
    private javax.swing.JTextField phn;
    private javax.swing.JTextField rg;
    // End of variables declaration//GEN-END:variables
}
