/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

/**
 *
 * @author Lenovo
 */
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
public class Register_customer extends javax.swing.JFrame {

    /**
     * Creates new form Register_customer
     */
    public Register_customer() {
        initComponents();
        this.hide.setVisible(false);
        this.hide2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spass = new javax.swing.JPasswordField();
        repass = new javax.swing.JPasswordField();
        Spass = new javax.swing.JLabel();
        Repass = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        cemail = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        btncusdone = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Back_button = new javax.swing.JButton();
        show = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        show2 = new javax.swing.JLabel();
        hide2 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        sq = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("customer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 120, 30));

        spass.setBackground(new java.awt.Color(0, 0, 0));
        spass.setForeground(new java.awt.Color(255, 255, 255));
        spass.setText("jPasswordField1");
        spass.setBorder(null);
        spass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spassFocusGained(evt);
            }
        });
        spass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spassActionPerformed(evt);
            }
        });
        jPanel1.add(spass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 280, 20));

        repass.setBackground(new java.awt.Color(0, 0, 0));
        repass.setForeground(new java.awt.Color(255, 255, 255));
        repass.setText("jPasswordField2");
        repass.setBorder(null);
        repass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                repassFocusGained(evt);
            }
        });
        repass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repassActionPerformed(evt);
            }
        });
        jPanel1.add(repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 280, 20));

        Spass.setForeground(new java.awt.Color(255, 255, 255));
        Spass.setText("Set Password");
        jPanel1.add(Spass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 280, -1));

        Repass.setForeground(new java.awt.Color(255, 255, 255));
        Repass.setText("Rewrite Password");
        jPanel1.add(Repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 280, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 280, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 280, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 280, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(149, 165, 166));
        jLabel8.setText(" X");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 20, 30));

        fn.setBackground(new java.awt.Color(0, 0, 0));
        fn.setForeground(new java.awt.Color(255, 255, 255));
        fn.setText("First_name");
        fn.setBorder(null);
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 280, 20));

        ln.setBackground(new java.awt.Color(0, 0, 0));
        ln.setForeground(new java.awt.Color(255, 255, 255));
        ln.setText("Last_name");
        ln.setBorder(null);
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 280, 20));

        cemail.setBackground(new java.awt.Color(0, 0, 0));
        cemail.setForeground(new java.awt.Color(255, 255, 255));
        cemail.setText("Email");
        cemail.setBorder(null);
        jPanel1.add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 280, 20));

        phn.setBackground(new java.awt.Color(0, 0, 0));
        phn.setForeground(new java.awt.Color(255, 255, 255));
        phn.setText("Phone Number");
        phn.setBorder(null);
        jPanel1.add(phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 280, 20));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 280, 30));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 10));

        btncusdone.setBackground(new java.awt.Color(0, 153, 153));
        btncusdone.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btncusdone.setForeground(new java.awt.Color(255, 255, 255));
        btncusdone.setText("DONE!");
        btncusdone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncusdoneActionPerformed(evt);
            }
        });
        jPanel1.add(btncusdone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 80, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("C A T E R .COM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 90, 30));

        Back_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\return 2.png")); // NOI18N
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        show.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\show3.png")); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showMousePressed(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, 20));

        hide.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\hide3.png")); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideMousePressed(evt);
            }
        });
        jPanel1.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, 20));

        show2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\show3.png")); // NOI18N
        show2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                show2MousePressed(evt);
            }
        });
        jPanel1.add(show2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, 20));

        hide2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\hide3.png")); // NOI18N
        hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide2MousePressed(evt);
            }
        });
        jPanel1.add(hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, 20));

        ans.setBackground(new java.awt.Color(0, 0, 0));
        ans.setForeground(new java.awt.Color(255, 255, 255));
        ans.setText("Answer");
        ans.setBorder(null);
        jPanel1.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 280, 20));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 280, 20));

        sq.setBackground(new java.awt.Color(0, 0, 0));
        sq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your nick name?", "What is your favourite dish?", "What is  your mother tongue?", " " }));
        jPanel1.add(sq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 280, 20));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Security Question");
        jLabel3.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                jLabel3AncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 280, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\background image3.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repassActionPerformed

    private void repassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repassFocusGained
        repass.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_repassFocusGained

    private void spassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spassActionPerformed

    private void spassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spassFocusGained
        spass.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_spassFocusGained

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
          this.hide();
        Custom_login a=new Custom_login();
        a.setVisible(true);
    }//GEN-LAST:event_Back_buttonActionPerformed

    private void showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMousePressed
        hide.setVisible(true);
        show.setVisible(false);
        spass.setEchoChar((char)0);        // TODO add your handling code here:
    }//GEN-LAST:event_showMousePressed

    private void hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMousePressed
        show.setVisible(true);
        hide.setVisible(false);
        spass.setEchoChar('*');// TODO add your handling code here:
    }//GEN-LAST:event_hideMousePressed

    private void show2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show2MousePressed
        hide2.setVisible(true);
        show2.setVisible(false);
        repass.setEchoChar((char)0);  // TODO add your handling code here:
    }//GEN-LAST:event_show2MousePressed

    private void hide2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MousePressed
        show2.setVisible(true);
        hide2.setVisible(false);
        repass.setEchoChar('*');// TODO add your handling code here:
    }//GEN-LAST:event_hide2MousePressed

    private void jLabel3AncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel3AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3AncestorMoved
   Connection con1;
   PreparedStatement insert;
    private void btncusdoneActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        String fname=fn.getText();
        String lname=ln.getText();
        String email=cemail.getText();
        
        String pass =spass.getText();
        String mobile =phn.getText();
        
        String secuirityq =(String)sq.getSelectedItem();
        String secuirityans =ans.getText();
        if(fname.isEmpty()||lname.isEmpty()||pass.isEmpty()||mobile.isEmpty()||email.isEmpty()||secuirityq.isEmpty()||secuirityans.isEmpty()){
            JOptionPane.showMessageDialog(this,"Every field must be filled.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                Class.forName("com.mysql.jdbc.Driver"); //Register the mysql driver
               
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
            insert = con1.prepareStatement("insert into customer (fname,lname,pass,mobile,email,secuirityq,secuirityans)values(?,?,?,?,?,?,?)");
            insert.setString(1,fname);
            insert.setString(2,lname);
             insert.setString(3,pass);
             insert.setString(4,mobile);
            insert.setString(5,email);
           
         
            
          
            insert.setString(6,secuirityq);
            insert.setString(7,secuirityans);
            
          
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thanks for registration!");
            setVisible(false);
            new Login_Form().setVisible(true);
            fn.setText("");
            ln.setText("");
            spass.setText("");
            phn.setText("");
            cemail.setText("");
            sq.setSelectedItem("");
            ans.setText("");
            fn.requestFocus();
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Register_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Register_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        
    }                                         

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_customer().setVisible(true);
            }
        });
    }

   private javax.swing.JButton Back_button;
    private javax.swing.JLabel Repass;
    private javax.swing.JLabel Spass;
    private javax.swing.JTextField ans;
    private javax.swing.JButton btncusdone;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel hide2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField phn;
    private javax.swing.JPasswordField repass;
    private javax.swing.JLabel show;
    private javax.swing.JLabel show2;
    private javax.swing.JPasswordField spass;
    private javax.swing.JComboBox<String> sq;
      
    }

