


/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Home;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;

/**
 *
 * @author Lenovo
 */
public class Register_cat extends javax.swing.JFrame {

    /**
     * Creates new form Register_cat
     */
    public Register_cat() {
        initComponents();
        this.hide3.setVisible(false);
        this.hide4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        reg = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cpass = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        crepass = new javax.swing.JPasswordField();
        cphn = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        cloc = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btncadone = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        show3 = new javax.swing.JLabel();
        hide3 = new javax.swing.JLabel();
        show4 = new javax.swing.JLabel();
        hide4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sq = new javax.swing.JComboBox<>();
        sans = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(174, 214, 241));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("     CATERER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 21, 170, -1));

        cname.setBackground(new java.awt.Color(0, 0, 0));
        cname.setForeground(new java.awt.Color(255, 255, 255));
        cname.setText("Name");
        cname.setBorder(null);
        cname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnameFocusGained(evt);
            }
        });
        jPanel1.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 335, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 335, 12));

        cmail.setBackground(new java.awt.Color(0, 0, 0));
        cmail.setForeground(new java.awt.Color(255, 255, 255));
        cmail.setText("Email");
        cmail.setBorder(null);
        cmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmailFocusGained(evt);
            }
        });
        jPanel1.add(cmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 335, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 335, 10));

        reg.setBackground(new java.awt.Color(0, 0, 0));
        reg.setForeground(new java.awt.Color(255, 255, 255));
        reg.setText("Registration Number");
        reg.setBorder(null);
        reg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regFocusGained(evt);
            }
        });
        jPanel1.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 335, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 335, 10));

        jLabel2.setBackground(new java.awt.Color(174, 214, 241));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Set Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 335, -1));

        cpass.setBackground(new java.awt.Color(0, 0, 0));
        cpass.setForeground(new java.awt.Color(255, 255, 255));
        cpass.setText("jPasswordField1");
        cpass.setBorder(null);
        cpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpassFocusGained(evt);
            }
        });
        jPanel1.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 335, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 335, 10));

        jLabel3.setBackground(new java.awt.Color(174, 214, 241));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rewrite Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 335, -1));

        crepass.setBackground(new java.awt.Color(0, 0, 0));
        crepass.setForeground(new java.awt.Color(255, 255, 255));
        crepass.setText("jPasswordField2");
        crepass.setBorder(null);
        crepass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                crepassFocusGained(evt);
            }
        });
        jPanel1.add(crepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 335, -1));

        cphn.setBackground(new java.awt.Color(0, 0, 0));
        cphn.setForeground(new java.awt.Color(255, 255, 255));
        cphn.setText("Phone Number");
        cphn.setBorder(null);
        cphn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cphnFocusGained(evt);
            }
        });
        jPanel1.add(cphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 335, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 335, 16));

        cloc.setBackground(new java.awt.Color(0, 0, 0));
        cloc.setForeground(new java.awt.Color(255, 255, 255));
        cloc.setText("Location");
        cloc.setBorder(null);
        cloc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clocFocusGained(evt);
            }
        });
        jPanel1.add(cloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 335, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 550, 55, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 550, 127, -1));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 335, 10));

        btncadone.setBackground(new java.awt.Color(0, 153, 153));
        btncadone.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btncadone.setForeground(new java.awt.Color(255, 255, 255));
        btncadone.setText("DONE!");
        btncadone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadoneActionPerformed(evt);
            }
        });
        jPanel1.add(btncadone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 91, 32));

        jLabel4.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 204));
        jLabel4.setText("C A T E R .COM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, 106, 26));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(149, 165, 166));
        jLabel5.setText(" X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 0, 21, -1));

        Back_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\return 2.png")); // NOI18N
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 25, 26));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 72, 37, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 0, 37, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(149, 165, 166));
        jLabel10.setText("    X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 43, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(149, 165, 166));
        jLabel11.setText("    X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 0, 43, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 335, 18));

        show3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\show3.png")); // NOI18N
        show3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                show3MousePressed(evt);
            }
        });
        jPanel1.add(show3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, 10));

        hide3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\hide3.png")); // NOI18N
        hide3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide3MousePressed(evt);
            }
        });
        jPanel1.add(hide3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 20, 10));

        show4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\show3.png")); // NOI18N
        show4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                show4MousePressed(evt);
            }
        });
        jPanel1.add(show4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 20, 10));

        hide4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\hide3.png")); // NOI18N
        hide4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hide4MousePressed(evt);
            }
        });
        jPanel1.add(hide4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, 10));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Security Question");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 330, -1));

        sq.setBackground(new java.awt.Color(0, 0, 0));
        sq.setForeground(new java.awt.Color(255, 255, 255));
        sq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your nick name?", "What is your favourite dish?", "What is  your mother tongue?", " " }));
        jPanel1.add(sq, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 330, -1));

        sans.setBackground(new java.awt.Color(0, 0, 0));
        sans.setForeground(new java.awt.Color(255, 255, 255));
        sans.setText("Answer");
        jPanel1.add(sans, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 330, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 557, 330, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\project image\\background image4.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
        this.hide();
        Custom_login frm=new Custom_login();
        frm.setVisible(true);
    }//GEN-LAST:event_Back_buttonActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void clocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clocFocusGained
        // TODO add your handling code here:
        cloc.setText("");
    }//GEN-LAST:event_clocFocusGained

    private void cphnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cphnFocusGained
        // TODO add your handling code here:
        cphn.setText("");
    }//GEN-LAST:event_cphnFocusGained

    private void crepassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_crepassFocusGained
        // TODO add your handling code here:
        crepass.setText("");
    }//GEN-LAST:event_crepassFocusGained

    private void cpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpassFocusGained
        // TODO add your handling code here:
        cpass.setText("");
    }//GEN-LAST:event_cpassFocusGained

    private void regFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regFocusGained
        // TODO add your handling code here:
        reg.setText("");
    }//GEN-LAST:event_regFocusGained

    private void cmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmailFocusGained
        // TODO add your handling code here:
        cmail.setText("");
    }//GEN-LAST:event_cmailFocusGained

    private void cnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusGained
        // TODO add your handling code here:
        cname.setText("");
    }//GEN-LAST:event_cnameFocusGained

    private void show3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show3MousePressed
        hide3.setVisible(true);
        show3.setVisible(false);
        cpass.setEchoChar((char)0);        // TODO add your handling code here:
    }//GEN-LAST:event_show3MousePressed

    private void hide3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide3MousePressed
        show3.setVisible(true);
        hide3.setVisible(false);
        cpass.setEchoChar('*');// TODO add your handling code here:
    }//GEN-LAST:event_hide3MousePressed

    private void show4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show4MousePressed
       hide4.setVisible(true);
        show4.setVisible(false);
        crepass.setEchoChar((char)0); 
    }//GEN-LAST:event_show4MousePressed

    private void hide4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide4MousePressed
        show4.setVisible(true);
        hide4.setVisible(false);
        crepass.setEchoChar('*');
    }//GEN-LAST:event_hide4MousePressed
Connection con1;
PreparedStatement insert;
    private void btncadoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadoneActionPerformed
        // TODO add your handling code here: 
        String name =cname.getText();
        String email =cmail.getText();
        String regno =reg.getText();
        String password =cpass.getText();
        String mobile =cphn.getText();
        String address =cloc.getText();
        String secuirityq =(String)sq.getSelectedItem();
        String secuirityans =sans.getText();
        if(name.isEmpty()||password.isEmpty()||regno.isEmpty()||mobile.isEmpty()||address.isEmpty()||email.isEmpty()||secuirityq.isEmpty()||secuirityans.isEmpty()){
            JOptionPane.showMessageDialog(this,"Every field must be filled.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                Class.forName("com.mysql.jdbc.Driver"); //Register the mysql driver
               
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/demo2","root","");
            insert = con1.prepareStatement("insert into caterer1 (name,email,password,regno,mobile,address,secuirityq,secuirityans)values(?,?,?,?,?,?,?,?)");
            insert.setString(1,name);
            insert.setString(2,email);
            insert.setString(3,password);
            insert.setString(4,regno);
            insert.setString(5,mobile);
            insert.setString(6,address);
            insert.setString(7,secuirityq);
            insert.setString(8,secuirityans);
            
          
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thanks for registration!");
            setVisible(false);
            new Login_Form().setVisible(true);
             this.dispose();
            cname.setText("");
            cmail.setText("");
            cpass.setText("");
            
            reg.setText("");
            cphn.setText("");
            cloc.setText("");
            sq.setSelectedItem("");
            sans.setText("");
            cname.requestFocus();
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Register_cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Register_cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btncadoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_cat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_button;
    private javax.swing.JButton btncadone;
    private javax.swing.JTextField cloc;
    private javax.swing.JTextField cmail;
    private javax.swing.JTextField cname;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JTextField cphn;
    private javax.swing.JPasswordField crepass;
    private javax.swing.JLabel hide3;
    private javax.swing.JLabel hide4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField sans;
    private javax.swing.JLabel show3;
    private javax.swing.JLabel show4;
    private javax.swing.JComboBox<String> sq;
    // End of variables declaration//GEN-END:variables
}
